# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/isaac/Desktop/Proyecto-Electrico-B52786

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/isaac/Desktop/Proyecto-Electrico-B52786

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isaac/Desktop/Proyecto-Electrico-B52786/CMakeFiles /home/isaac/Desktop/Proyecto-Electrico-B52786//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isaac/Desktop/Proyecto-Electrico-B52786/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named deWAFF

# Build rule for target.
deWAFF: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 deWAFF
.PHONY : deWAFF

# fast build rule for target.
deWAFF/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/build
.PHONY : deWAFF/fast

src/deWAFF.o: src/deWAFF.cpp.o
.PHONY : src/deWAFF.o

# target to build an object file
src/deWAFF.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/deWAFF.cpp.o
.PHONY : src/deWAFF.cpp.o

src/deWAFF.i: src/deWAFF.cpp.i
.PHONY : src/deWAFF.i

# target to preprocess a source file
src/deWAFF.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/deWAFF.cpp.i
.PHONY : src/deWAFF.cpp.i

src/deWAFF.s: src/deWAFF.cpp.s
.PHONY : src/deWAFF.s

# target to generate assembly for a file
src/deWAFF.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/deWAFF.cpp.s
.PHONY : src/deWAFF.cpp.s

src/laplacian.o: src/laplacian.cpp.o
.PHONY : src/laplacian.o

# target to build an object file
src/laplacian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/laplacian.cpp.o
.PHONY : src/laplacian.cpp.o

src/laplacian.i: src/laplacian.cpp.i
.PHONY : src/laplacian.i

# target to preprocess a source file
src/laplacian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/laplacian.cpp.i
.PHONY : src/laplacian.cpp.i

src/laplacian.s: src/laplacian.cpp.s
.PHONY : src/laplacian.s

# target to generate assembly for a file
src/laplacian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/laplacian.cpp.s
.PHONY : src/laplacian.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parallel_deWAFF.o: src/parallel_deWAFF.cpp.o
.PHONY : src/parallel_deWAFF.o

# target to build an object file
src/parallel_deWAFF.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/parallel_deWAFF.cpp.o
.PHONY : src/parallel_deWAFF.cpp.o

src/parallel_deWAFF.i: src/parallel_deWAFF.cpp.i
.PHONY : src/parallel_deWAFF.i

# target to preprocess a source file
src/parallel_deWAFF.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/parallel_deWAFF.cpp.i
.PHONY : src/parallel_deWAFF.cpp.i

src/parallel_deWAFF.s: src/parallel_deWAFF.cpp.s
.PHONY : src/parallel_deWAFF.s

# target to generate assembly for a file
src/parallel_deWAFF.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/parallel_deWAFF.cpp.s
.PHONY : src/parallel_deWAFF.cpp.s

src/timer.o: src/timer.cpp.o
.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i
.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s
.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/tools.o: src/tools.cpp.o
.PHONY : src/tools.o

# target to build an object file
src/tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/tools.cpp.o
.PHONY : src/tools.cpp.o

src/tools.i: src/tools.cpp.i
.PHONY : src/tools.i

# target to preprocess a source file
src/tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/tools.cpp.i
.PHONY : src/tools.cpp.i

src/tools.s: src/tools.cpp.s
.PHONY : src/tools.s

# target to generate assembly for a file
src/tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deWAFF.dir/build.make CMakeFiles/deWAFF.dir/src/tools.cpp.s
.PHONY : src/tools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... deWAFF"
	@echo "... src/deWAFF.o"
	@echo "... src/deWAFF.i"
	@echo "... src/deWAFF.s"
	@echo "... src/laplacian.o"
	@echo "... src/laplacian.i"
	@echo "... src/laplacian.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parallel_deWAFF.o"
	@echo "... src/parallel_deWAFF.i"
	@echo "... src/parallel_deWAFF.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/tools.o"
	@echo "... src/tools.i"
	@echo "... src/tools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

